Only run incremental rpc update if firewall is up at all
Also print an informative message if we do update rules.

(cherry picked from commit 5638ce1e1ce5fcb01f99c476cd1a831d6562d46e)

diff --git a/SuSEfirewall2 b/SuSEfirewall2
--- a/SuSEfirewall2
+++ b/SuSEfirewall2
@@ -1603,6 +1603,13 @@ cibiz()
     esac
 }
 
+# returns zero if the firewall is currently considered to be running, non-zero
+# otherwise
+is_firewall_running()
+{
+    /bin/systemctl -q is-active SuSEfirewall2 || return 1
+}
+
 # returns a safe identifier to use for the iptables comment module
 # input:
 # $1: the base identifier to use
@@ -2784,7 +2791,7 @@ function update_rpc()
 	remove_matching_rules "rpc.$pattern"
 	# necessary to reduce the input_zones to the necessary amount
 	protect_from_internal "update-rpc"
-	
+
 	local action
 	for action in DROP REJECT; do
 		reject_or_drop_services $action "update-rpc" $service
@@ -2912,6 +2919,11 @@ fi
 
 if [ "$ACTION" = "update-rpc" ]; then
     init_configuration
+    if ! is_firewall_running; then
+        die 1 "SuSEfirewall2 is not running, no rpc update possible"
+    else
+	message "Updating rules for ${rpc_service:-every} rpc service"
+    fi
     update_rpc $rpc_service
     die 0
 fi
