make sure we don't load custom rules from a world writable file
Otherwise this would be a security nightmare... admins might copy over
shell scripts with different ownership/permissions than it is healthy
for this purpose.

diff --git a/SuSEfirewall2 b/SuSEfirewall2
--- a/SuSEfirewall2
+++ b/SuSEfirewall2
@@ -511,6 +511,35 @@ function get_iptables()
 	esac
 }
 
+# sources the given file, but only if it has safe permissions and ownership
+function source_safe()
+{
+	local file="$1"
+	bits=`/usr/bin/stat -c %A "$file"`
+	if [ $? -ne 0 ]; then
+		echo "Cannot stat file $file to be sourced" 1>&2
+		return 1
+	fi
+	owner=`/usr/bin/stat -c %u "$file"`
+	group=`/usr/bin/stat -c %g "$file"`
+
+	world_write_bit=${bits:8:1}
+
+	if [ ${world_write_bit} != "-" -o "$owner" -ne 0 -o "$group" -ne 0 ]; then
+		echo "Unsafe permissions for file $file to be sourced" 1>&2
+		return 1
+	fi
+
+	. "$file"
+	res=$?
+	if [ $res -ne 0 ]; then
+		echo "failed to source $file: returned $res" 1>&2
+		return 1
+	fi
+
+	return 0
+}
+
 # parameters: protocol port variable
 # check whether $1 and $2/$3 are a valid protocol/port combination and sets global
 # variables $proto, $port ($rport) and $sport ($rsport) in iptables syntax
@@ -1115,14 +1144,15 @@ process_masq_dev()
 
 load_customrules()
 {
-    ### Load custom rules
-    if [ -n "$FW_CUSTOMRULES" ]; then
-	if [ ! -r "$FW_CUSTOMRULES" ]; then
-	    die 1 "Firewall custom rules file can not be read from $FW_CUSTOMRULES"
+	### Load custom rules
+	if [ -n "$FW_CUSTOMRULES" ]; then
+		source_safe "$FW_CUSTOMRULES"
+		if [ $? -eq 0 ]; then
+			message "Firewall custom rules loaded from $FW_CUSTOMRULES"
+		else
+			die 1 "Failed to load custom rules"
+		fi
 	fi
-	. "$FW_CUSTOMRULES"
-	message "Firewall custom rules loaded from $FW_CUSTOMRULES"
-    fi
 }
 
 check_interfaces()
