- fall back to normal iptables if iptables-batch fails - always add ip6tables drop rule in case REJECT doesn't work for some   reason
git-svn-id: https://forgesvn1.novell.com/svn/susefirewall2/trunk@130 b36d0de6-17df-0310-aa5c-c2ebc275e154

diff --git a/SuSEfirewall2-batch b/SuSEfirewall2-batch
--- a/SuSEfirewall2-batch
+++ b/SuSEfirewall2-batch
@@ -67,8 +67,18 @@ commit_iptables_batch()
 {
     if [ -n "$USE_IPTABLES_BATCH" ]; then
 	message "batch committing..."
-	$IPTABLES_BATCH "$iptables_batchfile"
-	$IP6TABLES_BATCH "$ip6tables_batchfile"
+	if ! $IPTABLES_BATCH "$iptables_batchfile"; then
+	    error "iptables-batch failed, re-running using iptables"
+	    iptables() { $IPTABLES_BIN "$@"; }
+	    commit() { :; }
+	    . $iptables_batchfile
+	fi
+	if ! $IP6TABLES_BATCH "$ip6tables_batchfile"; then
+	    error "ip6tables-batch failed, re-running using ip6tables"
+	    ip6tables() { $IP6TABLES_BIN "$@"; }
+	    commit() { :; }
+	    . $ip6tables_batchfile
+	fi
     fi
 }
 
